name: Build and Deploy Plugin

on:
  push:
    branches:
      - main
      - 'release/*'  # Trigger on release branches as well
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 17 (adjust to JDK version of your choice)
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      # Cache Maven dependencies (optional, but speeds up the build)
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Run Maven build
      - name: Build with Maven
        run: mvn clean install --batch-mode

      # Optionally, deploy or perform additional tasks
      # - name: Deploy Plugin
      #   run: ./deploy-script.sh

