name: Build and Deploy Plugin

on:
  push:
    branches:
      - main
  workflow_dispatch:  # This allows for manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Specify the version you need
          distribution: 'openjdk'  # Use Temurin (Adoptium's JDK distribution)

      - name: Build with Maven
        run: mvn clean install --batch-mode
