name: Java CI with Maven

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger on
  pull_request:
    branches:
      - main  # Replace with the branch you want to trigger on

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adoptopenjdk'

    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/*.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Run mvn clean install
      run: mvn clean install --batch-mode --no-transfer-progress
